### PR TITLE
Added pipx support

### PR DESCRIPTION
**Pull request by 0xPreDa**
Hello !

Recently, i was a little bit annoyed when using pywhisker because of the pyOpenSSL library changes that makes errors when creating the .pfx file. So i wanted to try converting my first project into a python package.

Before :
before

Now it's working fine using pyOpenSSL=22.1.0 into a pipx package :

```
git clone https://github.com/0xPreDa/pywhisker.git
pipx install .
```
After : 
after

I made some changes on the code structure to help me debugging and prevent issues with variables. Let me know if it's fine for you.
You can now build it to Pypi to make it downloadable remotely and usable in Exegol ❤️

### CODE REVIEW

**Comment by QU35T-code** [comment]
Thanks @0xPreDa,

This PR will be reviewed carefully since you moved the code. The diff shows it as a new addition, so the code needs to be thoroughly checked to ensure that no "backdoors" are introduced into the project :)

**Comment by ShutdownRepo** [comment]
Hi @0xPreDa thank you for the great addition
However, as @QU35T-code indicated, the diff shows the whole pywhisker.py file as added.
It may be an error, since the `pywhisker.py` file seems to have been moved to `pywhisker/ShadowCredentials.py` and a new `pywhisker/pywhisker.py` file added.

This can't be merged in its current state. Is there anything you can do to propose a new PR (or fix the current one) with a better diff ?

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
probable human error in moving files around, cf. the latest comment

**Comment by ShutdownRepo** [comment]
Oh okay that's why, thank you for the explanation
Let's close this PR and make another one : focus on the 3 first steps you described earlier, they will be easy to review
Then, I will proceed to the 4 next steps, and will need you to review the PR to make sure I didn't mess things up, if that's alright with you 🙏

**Pull request closed without merging**
